apiVersion: v1
kind: Service
metadata:
  name: jenkins-expose
  namespace: ci
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
  ports:
    - port: 8080 # Internal service port
      targetPort: 8080 # Your application's container port
      nodePort: 4001 # MUST match any of the containerPort from cluster config
